### ISSUE TITLE
about - Shimmer

### ISSUE THREAD

**Issue by Shimmer66** [Shimmer66/GitalkComment#3]
https://shimmer66.github.io/about/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

**Comment by Shimmer66** [comment]
啦啦啦啦啦啦

**Comment by Shimmer66** [comment]
lalalalalallalalalalalalallalalalalalalalla

**Comment by Shimmer66** [comment]
崩了呀

**Comment by Amore-e** [comment]
厉害了姐妹儿

**Comment by Amore-e** [comment]
白日依山尽，黄河入海流。欲穷千里目，更上一层楼。
加油！姐妹儿

**Comment by LUCKnan** [comment]
我想当一个诗人的时候，
我就失去了诗，
我想当一个人的时候，
我就失去了我自己。
在你什么也不想要的时候，
一切如期而来。          
                                                                                                                   ——顾城

**Comment by LUCKnan** [comment]
冯涛涛，加油呀！

**Comment by Shimmer66** [comment]
我要你在这寡淡的世上，深情地活.

**Comment by Shimmer66** [comment]
?????

**Comment by Shimmer66** [comment]
I don't konw.

**Comment by Shimmer66** [comment]
曾经的,都走散,

**Comment by LUCKnan** [comment]
中午好！

**Comment by Shimmer66** [comment]
会者定离，一期一会。
